In [155]:
import pandas as pd

In [180]:
import seaborn as sns

from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, precision_score

In [181]:
heart_df = pd.read_csv("1-heart.csv")

In [182]:
heart_df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [183]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [184]:
heart_df["target"].nunique()

2

In [185]:
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [186]:
x = heart_df.drop("target",axis =1)

In [187]:
y = heart_df["target"]

In [188]:
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [189]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [190]:
x.shape

(303, 13)

In [191]:
y.shape

(303,)

In [192]:
#Train Test Split 

x_train, x_test, y_train, y_test = train_test_split(
    x,y, test_size = 0.2, random_state = 42
)

In [193]:
y_train[y_train == 1] # vals = 133

132    1
75     1
59     1
93     1
6      1
      ..
121    1
20     1
71     1
106    1
102    1
Name: target, Length: 133, dtype: int64

In [194]:
y_train[y_train==0] # vals =109

202    0
196    0
176    0
177    0
258    0
      ..
257    0
214    0
302    0
188    0
270    0
Name: target, Length: 109, dtype: int64

In [195]:
model = LogisticRegression(max_iter = 1000)

In [196]:
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [197]:
y_pred = model.predict(x_test)

In [198]:
print("accuracy:", accuracy_score(y_test,y_pred))

accuracy: 0.8852459016393442

In [199]:
print("Precision Score :", precision_score(y_test,y_pred))

Precision Score : 0.8787878787878788

In [201]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))
print("Accuracy Score is :",accuracy_score(y_test,y_pred))
print("precision Score is :",precision_score(y_test,y_pred))
print("Recall Score is :",recall_score(y_test,y_pred))
print("f1 Score is :",f1_score(y_test,y_pred))

[[25  4]
 [ 3 29]]
              precision    recall  f1-score   support

           0       0.89      0.86      0.88        29
           1       0.88      0.91      0.89        32

    accuracy                           0.89        61
   macro avg       0.89      0.88      0.88        61
weighted avg       0.89      0.89      0.89        61

Accuracy Score is : 0.8852459016393442
precision Score is : 0.8787878787878788
Recall Score is : 0.90625
f1 Score is : 0.8923076923076924

In [132]:
#Scaling 

from sklearn.preprocessing import StandardScaler

In [133]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

In [134]:
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print("accuracy:", accuracy_score(y_test,y_pred))
print("Precision Score :", precision_score(y_test,y_pred))

accuracy: 0.8524590163934426
Precision Score : 0.8709677419354839